[watsonx]
api_key = "AaTSagg_V5MFzhd7Obl1JWucKOs01zD_YkpokfKLFqvP"
url = "https://us-south.ml.cloud.ibm.com/"
project_id = "4d06cf15-5f29-4c58-8722-7c8a3caf383c"

[models]
coordinator_id = "ibm/granite-3-8b-instruct"
predictive_id = "meta-llama/llama-3-3-70b-instruct"
sentiment_id = "meta-llama/llama-3-3-70b-instruct"

[models.coordinator_parameters]
decoding_method = "greedy"
max_new_tokens = 2000
temperature = 0.1
top_p = 0.9
top_k = 50

[models.predictive_parameters]
decoding_method = "greedy"
max_new_tokens = 1500
temperature = 0.3
repetition_penalty = 1.1

[models.sentiment_parameters]
decoding_method = "greedy"
max_new_tokens = 1500
min_new_tokens = 1
temperature = 0.3
top_k = 50
top_p = 0.9
repetition_penalty = 1.2